# Generated by Django 4.0.4 on 2022-05-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Addresse'},
        ),
        migrations.AlterModelOptions(
            name='personaldetails',
            options={'verbose_name': 'Personal Detail'},
        ),
    ]
